#!/bin/bash

# =============================================================================
# OddsStream Deployment Script for Local Network
# =============================================================================

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}🚀 Starting OddsStream Local Deployment${NC}\n"

# 1. Environment Setup
# -----------------------------------------------------------------------------
# Assuming we are running from inside the 'contract/' directory
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WASM_TARGET="wasm32-unknown-unknown"
LOCAL_RPC="https://faucet.testnet-conway.linera.net"

# Get the default chain ID from the local wallet
echo -e "${YELLOW}🔍 Detecting Local Chain ID...${NC}"
LINERA_CHAIN_ID=$(linera wallet show | grep -o "chain-[a-f0-9]\{64\}" | head -1)

if [[ -z "$LINERA_CHAIN_ID" ]]; then
    echo -e "${YELLOW}⚠️  No Chain ID found. Initializing wallet...${NC}"
    linera wallet init --faucet "$LOCAL_RPC"
    linera wallet request-chain --faucet "$LOCAL_RPC"
    LINERA_CHAIN_ID=$(linera wallet show | grep -o "chain-[a-f0-9]\{64\}" | head -1)
fi

echo -e "${GREEN}✓ Using Chain ID: $LINERA_CHAIN_ID${NC}"

# 2. Build Contracts
# -----------------------------------------------------------------------------
build_contract() {
    local name=$1
    local path=$2
    echo -e "\n${GREEN}🔨 Building $name...${NC}"
    
    cd "$PROJECT_ROOT/$path"
    cargo build --release --target $WASM_TARGET
    
    # Return the path to the wasm file
    echo "$PROJECT_ROOT/target/$WASM_TARGET/release/${name//-/_}.wasm"
}

SERVICE_WASM=$(build_contract "oddsstream-service" "contracts/service")
MARKET_WASM=$(build_contract "oddsstream-market" "contracts/market")
ORACLE_WASM=$(build_contract "oddsstream-oracle" "contracts/oracle")

# 3. Publish Bytecode
# -----------------------------------------------------------------------------
echo -e "\n${GREEN}📤 Publishing Bytecode...${NC}"

publish() {
    local wasm=$1
    linera project publish "$wasm" | grep -o "BytecodeId(\"[^\"]*\")" | sed 's/BytecodeId("//;s/")//'
}

SERVICE_BYTECODE=$(publish "$SERVICE_WASM")
echo "Service Bytecode: $SERVICE_BYTECODE"

MARKET_BYTECODE=$(publish "$MARKET_WASM")
echo "Market Bytecode:  $MARKET_BYTECODE"

ORACLE_BYTECODE=$(publish "$ORACLE_WASM")
echo "Oracle Bytecode:  $ORACLE_BYTECODE"

# 4. Create Applications
# -----------------------------------------------------------------------------
echo -e "\n${GREEN}🌱 Creating Applications...${NC}"

create_app() {
    local bytecode=$1
    local json_args=$2
    linera project create-and-deploy "$bytecode" --json-argument "$json_args" \
        | grep -o "ApplicationId(\"[^\"]*\")" | sed 's/ApplicationId("//;s/")//'
}

# A. Registry Service
SERVICE_APP_ID=$(create_app "$SERVICE_BYTECODE" "{}")
echo "Registry App ID: $SERVICE_APP_ID"

# B. Oracle Adjudicator
ORACLE_APP_ID=$(create_app "$ORACLE_BYTECODE" '{
  "tee_public_key": "local-test-key",
  "committee_size": 1,
  "stake_amount": "100"
}')
echo "Oracle App ID:   $ORACLE_APP_ID"

# C. Example Market
MARKET_APP_ID=$(create_app "$MARKET_BYTECODE" '{
  "market_id": "local-match-001",
  "description": "Local Test: Team A vs Team B",
  "oracle_type": "Hybrid",
  "resolution_time": "2026-01-01T00:00:00Z",
  "registry_chain": "'$LINERA_CHAIN_ID'",
  "oracle_adjudicator": "'$ORACLE_APP_ID'"
}')
echo "Market App ID:   $MARKET_APP_ID"

# 5. Initialization
# -----------------------------------------------------------------------------
echo -e "\n${GREEN}🔗 Wiring Contracts...${NC}"

# Register Oracle
linera contract call "$SERVICE_APP_ID" \
    --operation '{"RegisterOracle": {"oracle_id": "'$ORACLE_APP_ID'"}}'

# Register Market
linera contract call "$SERVICE_APP_ID" \
    --operation '{"RegisterMarket": {
      "market_id": "local-match-001",
      "app_id": "'$MARKET_APP_ID'",
      "description": "Local Test: Team A vs Team B"
    }}'

# 6. Generate Frontend Config
# -----------------------------------------------------------------------------
echo -e "\n${GREEN}📝 Generating Frontend Config...${NC}"

CONFIG_PATH="$PROJECT_ROOT/frontend/src/config/local.ts"
mkdir -p "$(dirname "$CONFIG_PATH")"

cat > "$CONFIG_PATH" << EOF
// Auto-generated by deploy_local.sh
export const LOCAL_CONFIG = {
  NETWORK: 'local' as const,
  RPC_URL: 'https://faucet.testnet-conway.linera.net',
  GRAPHQL_URL: 'https://faucet.testnet-conway.linera.net',
  WS_URL: 'wss://faucet.testnet-conway.linera.net/ws',

  APPLICATIONS: {
    REGISTRY: '$SERVICE_APP_ID',
    ORACLE_ADJUDICATOR: '$ORACLE_APP_ID',
    EXAMPLE_MARKET: '$MARKET_APP_ID'
  },
  
  CHAIN_ID: '$LINERA_CHAIN_ID'
};

export default LOCAL_CONFIG;
EOF

echo -e "${GREEN}✅ Deployment Complete! Config written to frontend/src/config/local.ts${NC}"