/**
 * OddsStream Configuration for Linera Conway Testnet
 * Auto-generated by deployment scripts - DO NOT EDIT MANUALLY
 */

// ============================================================================
// Conway Testnet Network Configuration
// ============================================================================
export const CONWAY_CONFIG = {
  // Network Identification
  NETWORK: 'conway' as const,
  NETWORK_ID: 'conway-testnet-2024',
  NETWORK_NAME: 'Linera Conway Testnet',
  NETWORK_COLOR: '#7c3aed',
  
  // RPC Endpoints
  RPC_URL: 'https://faucet.testnet-conway.linera.net',
  GRAPHQL_URL: 'https://faucet.testnet-conway.linera.net/graphql',
  WS_URL: 'wss://faucet.testnet-conway.linera.net/ws',
  
  // Faucet & Test Tokens
  FAUCET_URL: 'https://faucet.testnet-conway.linera.net',
  DEFAULT_TOKEN_SYMBOL: 'LIN',
  DEFAULT_TOKEN_DECIMALS: 18,
  
  // Block Explorer
  EXPLORER_URL: 'https://explorer.testnet-conway.linera.net',
  
  // ==========================================================================
  // Application IDs (Auto-populated during deployment)
  // ==========================================================================
  APPLICATIONS: {
    // Registry Service (manages all markets)
    REGISTRY: '0xe47c5c8b1c5b5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5',
    
    // Oracle Adjudicator (hybrid TEE/committee oracle)
    ORACLE_ADJUDICATOR: '0xf57c5c8b1c5b5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5',
    
    // Example Markets (pre-deployed for testing)
    EXAMPLE_MARKETS: [
      {
        id: 'market-001',
        appId: '0xc47c5c8b1c5b5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5',
        name: 'FC Barcelona vs Real Madrid',
        description: 'Will FC Barcelona win against Real Madrid?',
        category: 'sports',
        oracleType: 'hybrid' as const,
        resolutionTime: '2024-12-01T20:00:00Z'
      },
      {
        id: 'market-002',
        appId: '0xd47c5c8b1c5b5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5',
        name: 'Bitcoin $50k by EOY',
        description: 'Will Bitcoin reach $50,000 by end of 2024?',
        category: 'crypto',
        oracleType: 'tee' as const,
        resolutionTime: '2024-12-31T23:59:59Z'
      },
      {
        id: 'market-003',
        appId: '0xa47c5c8b1c5b5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5',
        name: 'AI Breakthrough by Q2',
        description: 'Will a major AI breakthrough be announced before June 2024?',
        category: 'technology',
        oracleType: 'committee' as const,
        resolutionTime: '2024-06-30T23:59:59Z'
      }
    ]
  },
  
  // ==========================================================================
  // Default Market Parameters
  // ==========================================================================
  DEFAULT_MARKET: {
    // Trading parameters
    FEE_PERCENTAGE: 1.5,           // 1.5% platform fee
    MIN_STAKE: 0.01,              // Minimum 0.01 LIN to participate
    MAX_STAKE: 10000,             // Maximum 10,000 LIN per order
    STAKE_STEP: 0.01,             // Minimum increment
    
    // Resolution parameters
    RESOLUTION_BUFFER_SECONDS: 300, // 5 minutes buffer for oracle resolution
    DISPUTE_PERIOD_SECONDS: 86400,  // 24 hours to dispute resolution
    
    // Liquidity parameters
    INITIAL_LIQUIDITY: 1000,       // Initial liquidity requirement for new markets
    MIN_LIQUIDITY: 100,            // Minimum liquidity to keep market active
  },
  
  // ==========================================================================
  // AI Agent Configuration
  // ==========================================================================
  AI_AGENT: {
    // Model Context Protocol (MCP) endpoints
    MCP_SERVER_URL: 'wss://mcp.testnet-conway.linera.net',
    MCP_GRAPHQL_ENDPOINT: 'https://mcp.testnet-conway.linera.net/graphql',
    
    // Default agent strategies
    DEFAULT_STRATEGIES: [
      {
        id: 'market-maker',
        name: 'Market Maker',
        description: 'Provides liquidity on both sides of the market',
        defaultParams: {
          spread: 0.02,           // 2% spread
          depthLevels: 5,         // 5 price levels
          rebalanceInterval: 30   // 30 seconds
        }
      },
      {
        id: 'arbitrage-bot',
        name: 'Arbitrage Bot',
        description: 'Exploits price differences across markets',
        defaultParams: {
          minProfitMargin: 0.01,  // 1% minimum profit
          maxPositionSize: 1000,
          cooldownSeconds: 10
        }
      },
      {
        id: 'trend-follower',
        name: 'Trend Follower',
        description: 'Follows momentum and market trends',
        defaultParams: {
          lookbackPeriod: 100,    // 100 data points
          momentumThreshold: 0.02, // 2% momentum
          stopLoss: 0.05          // 5% stop loss
        }
      }
    ],
    
    // Agent marketplace
    AGENT_MARKETPLACE_ENABLED: true,
    AGENT_STAKE_REQUIREMENT: 100, // 100 LIN staked to list an agent
    AGENT_FEE_PERCENTAGE: 10,     // 10% fee on agent profits
  },
  
  // ==========================================================================
  // Wallet & Authentication
  // ==========================================================================
  WALLET: {
    // Supported wallet providers (Conway integrates Dynamic wallet)
    PROVIDERS: ['dynamic', 'linera', 'metamask'] as const,
    
    // Dynamic wallet configuration (Conway's integrated solution)
    DYNAMIC_CONFIG: {
      environmentId: 'conway-testnet',
      appName: 'OddsStream',
      appLogoUrl: 'https://oddsstream.xyz/logo.png',
      theme: 'dark' as const,
      network: 'conway-testnet',
      defaultChainId: 'conway',
    },
    
    // Session management
    SESSION_TIMEOUT_MINUTES: 30,
    AUTO_RECONNECT: true,
    MULTICHAIN_SUPPORT: true,     // Users can have multiple microchains
  },
  
  // ==========================================================================
  // UI & Display Configuration
  // ==========================================================================
  UI: {
    // Real-time update intervals (in milliseconds)
    UPDATE_INTERVALS: {
      MARKET_DATA: 1000,          // 1 second for market data
      ORDER_BOOK: 500,            // 500ms for order book
      USER_BALANCE: 5000,         // 5 seconds for balances
      SYSTEM_STATUS: 30000,       // 30 seconds for system status
    },
    
    // Default display settings
    DEFAULT_THEME: 'dark' as const,
    DEFAULT_CURRENCY: 'USD',
    NUMBER_FORMAT: {
      DECIMALS: 2,
      USE_GROUPING: true,
      MIN_FRACTION_DIGITS: 2,
      MAX_FRACTION_DIGITS: 4,
    },
    
    // Chart configuration
    CHARTS: {
      DEFAULT_TIMEFRAME: '1h',
      CANDLE_INTERVALS: ['1m', '5m', '15m', '1h', '4h', '1d'],
      INDICATORS: ['sma', 'ema', 'rsi', 'macd', 'volume'],
      COLOR_SCHEME: {
        bullish: '#10b981',
        bearish: '#ef4444',
        neutral: '#6b7280',
        volume: '#8b5cf6',
      }
    },
  },
  
  // ==========================================================================
  // Performance & Monitoring
  // ==========================================================================
  PERFORMANCE: {
    // Cross-chain message configuration
    MESSAGE_BATCH_SIZE: 10,       // Max orders per batch
    MESSAGE_TIMEOUT_MS: 30000,    // 30 second timeout
    MESSAGE_RETRY_ATTEMPTS: 3,
    
    // Cache configuration
    CACHE_TTL: {
      MARKET_LIST: 30000,         // 30 seconds
      MARKET_DETAILS: 10000,      // 10 seconds
      USER_POSITIONS: 15000,      // 15 seconds
      ORACLE_DATA: 60000,         // 1 minute
    },
    
    // Monitoring endpoints
    HEALTH_CHECK_URL: 'https://health.testnet-conway.linera.net',
    METRICS_ENDPOINT: 'https://metrics.testnet-conway.linera.net',
  },
  
  // ==========================================================================
  // Feature Flags
  // ==========================================================================
  FEATURES: {
    ENABLE_BATCHED_ORDERS: true,
    ENABLE_AI_AGENTS: true,
    ENABLE_TEE_ORACLE: true,
    ENABLE_COMMITTEE_ORACLE: true,
    ENABLE_MARKET_CREATION: true,
    ENABLE_SOCIAL_TRADING: false,  // Coming soon
    ENABLE_DERIVATIVES: false,     // Coming soon
  },
  
  // ==========================================================================
  // API Keys & External Services
  // ==========================================================================
  EXTERNAL: {
    // Price feeds (for USD conversion)
    COINGECKO_API: 'https://api.coingecko.com/api/v3',
    
    // Sports data (for sports markets)
    SPORTS_DATA_API: 'https://v1.oddsstream.sportsdata.io',
    
    // TEE Oracle providers
    TEE_PROVIDERS: [
      {
        name: 'Intel SGX',
        endpoint: 'https://sgx-oracle.testnet-conway.linera.net',
        publicKey: '0x...',
        attestationService: 'https://api.trustedservices.intel.com/sgx/dev'
      },
      {
        name: 'AMD SEV',
        endpoint: 'https://sev-oracle.testnet-conway.linera.net',
        publicKey: '0x...',
        attestationService: 'https://api.amd.com/sev'
      }
    ],
    
    // Notification service
    PUSH_NOTIFICATIONS: {
      endpoint: 'https://notify.testnet-conway.linera.net',
      vapidKey: 'BP...'
    },
  }
} as const;

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Get the full GraphQL endpoint URL
 */
export function getGraphQLEndpoint(): string {
  return CONWAY_CONFIG.GRAPHQL_URL;
}

/**
 * Get WebSocket endpoint for real-time subscriptions
 */
export function getWebSocketEndpoint(): string {
  return CONWAY_CONFIG.WS_URL;
}

/**
 * Get application ID for a specific market
 */
export function getMarketAppId(marketId: string): string | undefined {
  const market = CONWAY_CONFIG.APPLICATIONS.EXAMPLE_MARKETS.find(m => m.id === marketId);
  return market?.appId;
}

/**
 * Check if a feature is enabled
 */
export function isFeatureEnabled(feature: keyof typeof CONWAY_CONFIG.FEATURES): boolean {
  return CONWAY_CONFIG.FEATURES[feature];
}

/**
 * Format LIN amount with proper decimals
 */
export function formatLinAmount(amount: string | number): string {
  const num = typeof amount === 'string' ? parseFloat(amount) : amount;
  return num.toLocaleString('en-US', {
    minimumFractionDigits: 2,
    maximumFractionDigits: CONWAY_CONFIG.DEFAULT_TOKEN_DECIMALS,
  });
}

/**
 * Calculate platform fee for a given amount
 */
export function calculateFee(amount: number): number {
  return amount * (CONWAY_CONFIG.DEFAULT_MARKET.FEE_PERCENTAGE / 100);
}

/**
 * Get the current network status
 */
export async function checkNetworkStatus(): Promise<{
  online: boolean;
  latency: number;
  blockHeight?: number;
}> {
  try {
    const start = Date.now();
    const response = await fetch(`${CONWAY_CONFIG.RPC_URL}/health`);
    const latency = Date.now() - start;
    
    if (response.ok) {
      const data = await response.json();
      return {
        online: true,
        latency,
        blockHeight: data.blockHeight,
      };
    }
    
    return { online: false, latency };
  } catch (error) {
    return { online: false, latency: 0 };
  }
}

/**
 * Generate a test account for development
 */
export function generateTestAccount(index: number = 0): {
  address: string;
  privateKey: string;
  chainId: string;
} {
  // Note: In production, this would be handled by the wallet
  const testAccounts = [
    {
      address: '0x742d35Cc6634C0532925a3b844Bc454e4438f44e',
      privateKey: '0x...', // Never expose real private keys
      chainId: 'chain-0x123...'
    },
    {
      address: '0x53d284357ec70cE289D6D64134DfAc8E511c8a3D',
      privateKey: '0x...',
      chainId: 'chain-0x456...'
    }
  ];
  
  return testAccounts[index % testAccounts.length];
}

// ============================================================================
// Type Export
// ============================================================================
export type ConwayConfig = typeof CONWAY_CONFIG;
export type MarketApp = typeof CONWAY_CONFIG.APPLICATIONS.EXAMPLE_MARKETS[0];
export type WalletProvider = typeof CONWAY_CONFIG.WALLET.PROVIDERS[number];
export type OracleType = 'tee' | 'committee' | 'hybrid';

export default CONWAY_CONFIG;